// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1zHMGE3ZHE7SuNHY5UvuetHycY5mH3mw',
    appId: '1:59522344272:web:d060690da0e338724cb855',
    messagingSenderId: '59522344272',
    projectId: 'playpal-app-123',
    authDomain: 'playpal-app-123.firebaseapp.com',
    storageBucket: 'playpal-app-123.firebasestorage.app',
    measurementId: 'G-TEQ29GD0FR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA32aVmAXN4VY2DB4L4qrlmWRxtKG0IqN0',
    appId: '1:59522344272:android:bf2b0dcb08914e5b4cb855',
    messagingSenderId: '59522344272',
    projectId: 'playpal-app-123',
    storageBucket: 'playpal-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs2Ep52A9eA9gHIkf9mXwpWRrYFdEmhFU',
    appId: '1:59522344272:ios:5509cf2e7fb559554cb855',
    messagingSenderId: '59522344272',
    projectId: 'playpal-app-123',
    storageBucket: 'playpal-app-123.firebasestorage.app',
    iosBundleId: 'com.example.playpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs2Ep52A9eA9gHIkf9mXwpWRrYFdEmhFU',
    appId: '1:59522344272:ios:5509cf2e7fb559554cb855',
    messagingSenderId: '59522344272',
    projectId: 'playpal-app-123',
    storageBucket: 'playpal-app-123.firebasestorage.app',
    iosBundleId: 'com.example.playpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1zHMGE3ZHE7SuNHY5UvuetHycY5mH3mw',
    appId: '1:59522344272:web:c409fc741a4ad4824cb855',
    messagingSenderId: '59522344272',
    projectId: 'playpal-app-123',
    authDomain: 'playpal-app-123.firebaseapp.com',
    storageBucket: 'playpal-app-123.firebasestorage.app',
    measurementId: 'G-7333WD8LNL',
  );

}